// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fqojdohrpxrksbezirys.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZxb2pkb2hycHhya3NiZXppcnlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI4MDg0MDAsImV4cCI6MjA4ODM4NDQwMH0.ufyj6-QXWKUpQFt3mjWkbm_os2kXKWrC0Kze8WAduek";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});